# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 8, 11, 6, 48, 41, 444756, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
