# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('title', models.CharField(default='New Resume', max_length=150, primary_key='true', serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('education', models.TextField()),
                ('work', models.TextField()),
                ('contact', models.CharField(max_length=500)),
                ('statement', models.TextField()),
                ('author', models.CharField(default='new user', max_length=140)),
                ('profile_pic', models.FileField(default='settings.MEDIA_ROOT/media/default.png', upload_to='')),
                ('portfolio', models.TextField()),
            ],
        ),
    ]
